<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Advik" failures="2" tests="8" name="MavenAutomationProject" time="0.136" errors="0" timestamp="2023-12-07T17:44:50 IST">
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase2" time="0.016">
    <skipped/>
  </testcase> <!-- verifyTestCase2 -->
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase2" time="0.001">
    <skipped/>
  </testcase> <!-- verifyTestCase2 -->
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase2" time="0.001">
    <skipped/>
  </testcase> <!-- verifyTestCase2 -->
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at failetestscripts.FailScriptsExecution.verifyTestCase2(FailScriptsExecution.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- verifyTestCase2 -->
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase3" time="0.001">
    <skipped/>
  </testcase> <!-- verifyTestCase3 -->
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase3" time="0.002">
    <skipped/>
  </testcase> <!-- verifyTestCase3 -->
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase3" time="0.002">
    <skipped/>
  </testcase> <!-- verifyTestCase3 -->
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at failetestscripts.FailScriptsExecution.verifyTestCase3(FailScriptsExecution.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- verifyTestCase3 -->
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase5" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTestCase5 -->
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase6" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTestCase6 -->
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase4" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTestCase4 -->
  <testcase classname="failetestscripts.FailScriptsExecution" name="verifyTestCase1" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTestCase1 -->
</testsuite> <!-- MavenAutomationProject -->
